import {
  subscribeToTasks,
  createManualTask,
  setTaskDone,
  softDeleteTask,
  updateTask,
  addComment,
  addAttachment,
  toggleSubtask,
  addSubtask,
  reassignTask,
  markTaskAsRead,
  removeTask,
  updateSubtasks,
  isTaskAssignedToUser,
  taskMatchesClient,
  duplicateTask,
  subscribeToTemplates,
  createTemplate,
  updateTemplate,
  deleteTemplate,
  deleteAllTemplates,
} from "@/lib/tasks";

export const taskService = {
  subscribeToTasks,
  createManualTask,
  setTaskDone,
  softDeleteTask,
  updateTask,
  addComment,
  addAttachment,
  toggleSubtask,
  addSubtask,
  reassignTask,
  markTaskAsRead,
  removeTask,
  updateSubtasks,
  isTaskAssignedToUser,
  taskMatchesClient,
  duplicateTask,
  subscribeToTemplates,
  createTemplate,
  updateTemplate,
  deleteTemplate,
  deleteAllTemplates,
};
