/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTasksRouteImport } from './routes/dashboard.tasks'
import { Route as DashboardTaskTemplatesRouteImport } from './routes/dashboard.task-templates'
import { Route as DashboardTargetsRouteImport } from './routes/dashboard.targets'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardEmployeesRouteImport } from './routes/dashboard.employees'
import { Route as DashboardClientsRouteImport } from './routes/dashboard.clients'
import { Route as DashboardCheckCompletedRouteImport } from './routes/dashboard.check-completed'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardApplicationsRouteImport } from './routes/dashboard.applications'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAccountingRouteImport } from './routes/dashboard.accounting'
import { Route as DashboardSettingsMigrationRouteImport } from './routes/dashboard.settings.migration'
import { Route as DashboardServiceServiceTypeRouteImport } from './routes/dashboard.service.$serviceType'
import { Route as DashboardDrivingSchoolVehiclesRouteImport } from './routes/dashboard.driving-school.vehicles'
import { Route as DashboardSettingsMigrationAccountingRouteImport } from './routes/dashboard.settings.migration.accounting'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTaskTemplatesRoute = DashboardTaskTemplatesRouteImport.update({
  id: '/task-templates',
  path: '/task-templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTargetsRoute = DashboardTargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmployeesRoute = DashboardEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCheckCompletedRoute = DashboardCheckCompletedRouteImport.update({
  id: '/check-completed',
  path: '/check-completed',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApplicationsRoute = DashboardApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountingRoute = DashboardAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsMigrationRoute =
  DashboardSettingsMigrationRouteImport.update({
    id: '/migration',
    path: '/migration',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardServiceServiceTypeRoute =
  DashboardServiceServiceTypeRouteImport.update({
    id: '/service/$serviceType',
    path: '/service/$serviceType',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDrivingSchoolVehiclesRoute =
  DashboardDrivingSchoolVehiclesRouteImport.update({
    id: '/driving-school/vehicles',
    path: '/driving-school/vehicles',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsMigrationAccountingRoute =
  DashboardSettingsMigrationAccountingRouteImport.update({
    id: '/accounting',
    path: '/accounting',
    getParentRoute: () => DashboardSettingsMigrationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/accounting': typeof DashboardAccountingRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/check-completed': typeof DashboardCheckCompletedRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/employees': typeof DashboardEmployeesRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/targets': typeof DashboardTargetsRoute
  '/dashboard/task-templates': typeof DashboardTaskTemplatesRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/driving-school/vehicles': typeof DashboardDrivingSchoolVehiclesRoute
  '/dashboard/service/$serviceType': typeof DashboardServiceServiceTypeRoute
  '/dashboard/settings/migration': typeof DashboardSettingsMigrationRouteWithChildren
  '/dashboard/settings/migration/accounting': typeof DashboardSettingsMigrationAccountingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/accounting': typeof DashboardAccountingRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/check-completed': typeof DashboardCheckCompletedRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/employees': typeof DashboardEmployeesRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/targets': typeof DashboardTargetsRoute
  '/dashboard/task-templates': typeof DashboardTaskTemplatesRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/driving-school/vehicles': typeof DashboardDrivingSchoolVehiclesRoute
  '/dashboard/service/$serviceType': typeof DashboardServiceServiceTypeRoute
  '/dashboard/settings/migration': typeof DashboardSettingsMigrationRouteWithChildren
  '/dashboard/settings/migration/accounting': typeof DashboardSettingsMigrationAccountingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/accounting': typeof DashboardAccountingRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/check-completed': typeof DashboardCheckCompletedRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/employees': typeof DashboardEmployeesRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/targets': typeof DashboardTargetsRoute
  '/dashboard/task-templates': typeof DashboardTaskTemplatesRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/driving-school/vehicles': typeof DashboardDrivingSchoolVehiclesRoute
  '/dashboard/service/$serviceType': typeof DashboardServiceServiceTypeRoute
  '/dashboard/settings/migration': typeof DashboardSettingsMigrationRouteWithChildren
  '/dashboard/settings/migration/accounting': typeof DashboardSettingsMigrationAccountingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/accounting'
    | '/dashboard/analytics'
    | '/dashboard/applications'
    | '/dashboard/billing'
    | '/dashboard/check-completed'
    | '/dashboard/clients'
    | '/dashboard/employees'
    | '/dashboard/leads'
    | '/dashboard/settings'
    | '/dashboard/targets'
    | '/dashboard/task-templates'
    | '/dashboard/tasks'
    | '/dashboard/'
    | '/dashboard/driving-school/vehicles'
    | '/dashboard/service/$serviceType'
    | '/dashboard/settings/migration'
    | '/dashboard/settings/migration/accounting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/accounting'
    | '/dashboard/analytics'
    | '/dashboard/applications'
    | '/dashboard/billing'
    | '/dashboard/check-completed'
    | '/dashboard/clients'
    | '/dashboard/employees'
    | '/dashboard/leads'
    | '/dashboard/settings'
    | '/dashboard/targets'
    | '/dashboard/task-templates'
    | '/dashboard/tasks'
    | '/dashboard'
    | '/dashboard/driving-school/vehicles'
    | '/dashboard/service/$serviceType'
    | '/dashboard/settings/migration'
    | '/dashboard/settings/migration/accounting'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/accounting'
    | '/dashboard/analytics'
    | '/dashboard/applications'
    | '/dashboard/billing'
    | '/dashboard/check-completed'
    | '/dashboard/clients'
    | '/dashboard/employees'
    | '/dashboard/leads'
    | '/dashboard/settings'
    | '/dashboard/targets'
    | '/dashboard/task-templates'
    | '/dashboard/tasks'
    | '/dashboard/'
    | '/dashboard/driving-school/vehicles'
    | '/dashboard/service/$serviceType'
    | '/dashboard/settings/migration'
    | '/dashboard/settings/migration/accounting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/task-templates': {
      id: '/dashboard/task-templates'
      path: '/task-templates'
      fullPath: '/dashboard/task-templates'
      preLoaderRoute: typeof DashboardTaskTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/targets': {
      id: '/dashboard/targets'
      path: '/targets'
      fullPath: '/dashboard/targets'
      preLoaderRoute: typeof DashboardTargetsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/employees': {
      id: '/dashboard/employees'
      path: '/employees'
      fullPath: '/dashboard/employees'
      preLoaderRoute: typeof DashboardEmployeesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients': {
      id: '/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/check-completed': {
      id: '/dashboard/check-completed'
      path: '/check-completed'
      fullPath: '/dashboard/check-completed'
      preLoaderRoute: typeof DashboardCheckCompletedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/applications': {
      id: '/dashboard/applications'
      path: '/applications'
      fullPath: '/dashboard/applications'
      preLoaderRoute: typeof DashboardApplicationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accounting': {
      id: '/dashboard/accounting'
      path: '/accounting'
      fullPath: '/dashboard/accounting'
      preLoaderRoute: typeof DashboardAccountingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/migration': {
      id: '/dashboard/settings/migration'
      path: '/migration'
      fullPath: '/dashboard/settings/migration'
      preLoaderRoute: typeof DashboardSettingsMigrationRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/service/$serviceType': {
      id: '/dashboard/service/$serviceType'
      path: '/service/$serviceType'
      fullPath: '/dashboard/service/$serviceType'
      preLoaderRoute: typeof DashboardServiceServiceTypeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/driving-school/vehicles': {
      id: '/dashboard/driving-school/vehicles'
      path: '/driving-school/vehicles'
      fullPath: '/dashboard/driving-school/vehicles'
      preLoaderRoute: typeof DashboardDrivingSchoolVehiclesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/migration/accounting': {
      id: '/dashboard/settings/migration/accounting'
      path: '/accounting'
      fullPath: '/dashboard/settings/migration/accounting'
      preLoaderRoute: typeof DashboardSettingsMigrationAccountingRouteImport
      parentRoute: typeof DashboardSettingsMigrationRoute
    }
  }
}

interface DashboardSettingsMigrationRouteChildren {
  DashboardSettingsMigrationAccountingRoute: typeof DashboardSettingsMigrationAccountingRoute
}

const DashboardSettingsMigrationRouteChildren: DashboardSettingsMigrationRouteChildren =
  {
    DashboardSettingsMigrationAccountingRoute:
      DashboardSettingsMigrationAccountingRoute,
  }

const DashboardSettingsMigrationRouteWithChildren =
  DashboardSettingsMigrationRoute._addFileChildren(
    DashboardSettingsMigrationRouteChildren,
  )

interface DashboardSettingsRouteChildren {
  DashboardSettingsMigrationRoute: typeof DashboardSettingsMigrationRouteWithChildren
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsMigrationRoute: DashboardSettingsMigrationRouteWithChildren,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteChildren {
  DashboardAccountingRoute: typeof DashboardAccountingRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardApplicationsRoute: typeof DashboardApplicationsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardCheckCompletedRoute: typeof DashboardCheckCompletedRoute
  DashboardClientsRoute: typeof DashboardClientsRoute
  DashboardEmployeesRoute: typeof DashboardEmployeesRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardTargetsRoute: typeof DashboardTargetsRoute
  DashboardTaskTemplatesRoute: typeof DashboardTaskTemplatesRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDrivingSchoolVehiclesRoute: typeof DashboardDrivingSchoolVehiclesRoute
  DashboardServiceServiceTypeRoute: typeof DashboardServiceServiceTypeRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountingRoute: DashboardAccountingRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardApplicationsRoute: DashboardApplicationsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardCheckCompletedRoute: DashboardCheckCompletedRoute,
  DashboardClientsRoute: DashboardClientsRoute,
  DashboardEmployeesRoute: DashboardEmployeesRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardTargetsRoute: DashboardTargetsRoute,
  DashboardTaskTemplatesRoute: DashboardTaskTemplatesRoute,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDrivingSchoolVehiclesRoute: DashboardDrivingSchoolVehiclesRoute,
  DashboardServiceServiceTypeRoute: DashboardServiceServiceTypeRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
